#ifndef HAL_IR_IR_PRV_H_
#define HAL_IR_IR_PRV_H_

#define HIR_LEADER_INTERVAL_MIN_US  12000UL
#define HIR_LEADER_INTERVAL_MAX_US  16000UL
#define HIR_ZERO_INTERVAL_MIN_US    900UL
#define HIR_ZERO_INTERVAL_MAX_US    1400UL
#define HIR_ONE_INTERVAL_MIN_US     1800UL
#define HIR_ONE_INTERVAL_MAX_US     2600UL

typedef enum
{
	HIR_WAIT_LEADER_START = 0,
	HIR_WAIT_LEADER_INTERVAL,
	HIR_RECEIVING_DATA
} HIR_State_t;

#endif /* HAL_IR_IR_PRV_H_ */
